import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, mkdirSync, existsSync, cpSync } from "fs";
import { dirname, resolve } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const prod = process.argv[2] === "production";
const outputDir = resolve(__dirname, "../zenith");

// Ensure output directory exists
if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true });
}

// Copy manifest.json
copyFileSync(resolve(__dirname, "manifest.source.json"), resolve(outputDir, "manifest.json"));

// Copy versions.json (maps plugin version → minAppVersion for Obsidian)
if (existsSync(resolve(__dirname, "versions.json"))) {
    copyFileSync(resolve(__dirname, "versions.json"), resolve(outputDir, "versions.json"));
}

// Sample third-party modules (source in modules_def/) → the built modules/ folder.
//
// `../zenith` is the LIVE plugin folder, and modules/ is now where the in-app
// installer writes what the user installs. Copying on every build would wipe
// that on the next `npm run dev`, so the sample is only seeded when the folder
// does not exist yet — or on an explicit `--with-sample`.
const modulesDir = resolve(__dirname, "modules_def");
const outModulesDir = resolve(outputDir, "modules");
const seedSample = process.argv.includes("--with-sample") || !existsSync(outModulesDir);
if (existsSync(modulesDir) && seedSample) {
    cpSync(modulesDir, outModulesDir, { recursive: true, force: true });
}

const banner = `/* 
 * Zenith — Obsidian Life Organizer Plugin
 * This is a generated/bundled file by esbuild.
 * Source: zenith-work/
 */`;


// ── JS Build ─────────────────────────────────────────
const jsContext = await esbuild.context({
    banner: { js: banner },
    entryPoints: [resolve(__dirname, "src/main.ts")],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins,
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    define: {
        "process.env.NODE_ENV": prod ? '"production"' : '"development"',
    },
    outfile: resolve(outputDir, "main.js"),
});

// ── CSS Build ────────────────────────────────────────
const cssContext = await esbuild.context({
    entryPoints: [resolve(__dirname, "src/styles/main.css")],
    bundle: true,
    outfile: resolve(outputDir, "styles.css"),
    logLevel: "info",
    minify: prod,
});

if (prod) {
    console.log("\n🔨 Zenith: Production build...\n");
    await jsContext.rebuild();
    await cssContext.rebuild();
    console.log("\n✅ Zenith: Build complete → ../zenith/\n");
    process.exit(0);
} else {
    console.log("\n👁️  Zenith: Watch mode started...\n");
    await jsContext.watch();
    await cssContext.watch();
}
