import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";
import { copyFileSync, mkdirSync, existsSync } from "fs";
import { dirname, resolve } from "path";
import { fileURLToPath } from "url";
import { outputDir } from "./scripts/paths.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const prod = process.argv[2] === "production";

// Ensure output directory exists
if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true });
}

// Copy manifest.json
copyFileSync(resolve(__dirname, "manifest.json"), resolve(outputDir, "manifest.json"));

// Copy versions.json (maps plugin version → minAppVersion for Obsidian)
if (existsSync(resolve(__dirname, "versions.json"))) {
    copyFileSync(resolve(__dirname, "versions.json"), resolve(outputDir, "versions.json"));
}

const banner = `/* 
 * Zenith — Obsidian Life Organizer Plugin
 * This is a generated/bundled file by esbuild.
 * Source: zenith-work/
 */`;


// ── JS Build ─────────────────────────────────────────
const jsContext = await esbuild.context({
    banner: { js: banner },
    entryPoints: [resolve(__dirname, "src/main.ts")],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtinModules,
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    define: {
        "process.env.NODE_ENV": prod ? '"production"' : '"development"',
    },
    outfile: resolve(outputDir, "main.js"),
});

// ── CSS Build ────────────────────────────────────────
const cssContext = await esbuild.context({
    entryPoints: [resolve(__dirname, "src/styles/main.css")],
    bundle: true,
    outfile: resolve(outputDir, "styles.css"),
    logLevel: "info",
    minify: prod,
});

if (prod) {
    console.log("\n🔨 Zenith: Production build...\n");
    await jsContext.rebuild();
    await cssContext.rebuild();
    console.log(`\n✅ Zenith: Build complete → ${outputDir}\n`);
    process.exit(0);
} else {
    console.log("\n👁️  Zenith: Watch mode started...\n");
    await jsContext.watch();
    await cssContext.watch();
}
