/**
 * Journal strings added with goals, quitting, the year in pixels, the daily
 * prompt and the rituals, merged into the dictionary in `core/i18n.ts`.
 */
export const JOURNAL_STRINGS: { en: Record<string, string>; ru: Record<string, string> } = {
    en: {
        'feature.journal.goals': 'Weekly goals and limits',
        'feature.journal.goals.desc':
            '“Three times a week”, “two coffees at most”, and days of rest (`sport: rest`) that neither break a streak nor add to it.',
        'feature.journal.quitHabits': 'Habits to quit',
        'feature.journal.quitHabits.desc':
            'A tracker for something you are giving up, counted over the days you recorded: “12 of 15 recorded days without it”.',

        'settings.journalTrackers.period': 'Goal',
        'settings.journalTrackers.period.day': 'Every day',
        'settings.journalTrackers.period.week': 'Days a week',
        'settings.journalTrackers.count': 'Days',
        'settings.journalTrackers.direction': 'Target is',
        'settings.journalTrackers.direction.atLeast': 'At least',
        'settings.journalTrackers.direction.atMost': 'At most',
        'settings.journalTrackers.mode': 'Habit',
        'settings.journalTrackers.mode.build': 'To keep',
        'settings.journalTrackers.mode.quit': 'To quit',
        'settings.journalTrackers.goalKept':
            'Days before today keep the goal they had — changing it does not rewrite the past.',

        'journal.quit.basis': '{kept} of {recorded} recorded days without {label}',
        'journal.goals.weekBasis.one': 'this week · {count} week kept in a row',
        'journal.goals.weekBasis.other': 'this week · {count} weeks kept in a row',
        'habits.rest': 'Rest day',

        'feature.journal.yearPixels': 'Year in pixels',
        'feature.journal.yearPixels.desc':
            'The whole year as squares, one a day, coloured by the mood or another tracker.',
        'journal.year.open': 'The year in pixels',
        'journal.year.month': 'Back to the month',
        'journal.year.prev': 'Previous year',
        'journal.year.next': 'Next year',
        'journal.year.this': 'This year',
        'journal.year.by': 'Coloured by',
        'journal.year.neutral': 'Grey: nothing recorded',

        'feature.journal.dailyPrompt': 'Question of the day',
        'feature.journal.dailyPrompt.desc':
            'One question a day in the check-in block, and in the template as {{prompt}}. Written into the note only when you ask.',
        'settings.journalPrompt': 'Questions',
        'settings.journalPrompt.desc':
            'A note with one question a line. Empty: a small built-in set in the interface language.',
        'settings.journalPrompt.placeholder': 'Templates/Questions.md',
        'journal.prompt.insert': 'Write it into the note',

        'feature.journal.rituals': 'Morning and evening rituals',
        'feature.journal.rituals.desc':
            'A short look at the day ahead in the morning, and at what got done in the evening. Commands, a dashboard card, and reminders if you want them.',
        'widget.ritual': 'Ritual',
        'ritual.off': 'Zenith: rituals are switched off (Journal → Features).',
        'ritual.morning.title': 'Morning',
        'ritual.evening.title': 'Evening review',
        'ritual.morning.remind': 'A look at the day ahead.',
        'ritual.evening.remind': 'A look back at the day.',
        'ritual.morning.today': 'Today',
        'ritual.morning.overdue': 'Left over from before',
        'ritual.evening.done': 'Done today',
        'ritual.evening.open': 'Not done',
        'ritual.evening.tomorrow': 'For tomorrow',
        'ritual.focus.pick': 'The main thing today',
        'ritual.focus.is': 'The main thing: {title}',
        'ritual.done': 'Done',
        'ritual.today': 'Today',
        'ritual.postpone': 'Tomorrow',
        'ritual.cancel': 'Drop',
        'ritual.failed': 'Zenith: that task has changed in its note — open it to see.',
        'ritual.empty.today': 'Nothing planned for today.',
        'ritual.empty.overdue': 'Nothing left over.',
        'ritual.empty.done': 'Nothing ticked off today — that is fine too.',
        'ritual.empty.open': 'Nothing left open.',
        'ritual.tomorrow.label': 'For tomorrow:',
        'ritual.tomorrow.placeholder': 'One line for the morning…',
        'ritual.tomorrow.save': 'Write into today’s note',
        'ritual.tomorrow.saved': 'Written into today’s note.',
        'ritual.close': 'Close',
        'ritual.card.open': 'Open',
        'ritual.card.tasks.one': '{count} task for today',
        'ritual.card.tasks.other': '{count} tasks for today',
        'settings.ritual': 'Rituals',
        'settings.ritual.morning': 'Morning at',
        'settings.ritual.evening': 'Evening at',
        'settings.ritual.reminders': 'Remind me',
        'settings.ritual.reminders.desc':
            'At those hours, in the notification center. A ritual missed while Obsidian was closed is not kept.',
        'settings.ritual.steps': 'Steps',
        'ritual.step.morning.today': 'Morning: today’s tasks',
        'ritual.step.morning.focus': 'Morning: the main thing',
        'ritual.step.morning.overdue': 'Morning: left over',
        'ritual.step.evening.done': 'Evening: done today',
        'ritual.step.evening.open': 'Evening: not done',
        'ritual.step.evening.tomorrow': 'Evening: a line for tomorrow',
        'feature.journal.reviews': 'Reviews',
        'feature.journal.reviews.desc':
            'Notes for the week, month, quarter and year, with a zenith-summary block that counts the period live — and freezes it into the note on request.',
        'feature.journal.yearInReview': 'Year in review',
        'feature.journal.yearInReview.desc':
            'The year read back from your notes: tasks, habits, mood, words, what you read, prayers and fasts. From 1 December, and for any past year.',
        'review.off': 'Reviews are switched off (Journal → Features).',
        'review.error.create':
            'Could not create the review note — check the folder and pattern in Journal settings.',
        'review.template.well': 'What went well',
        'review.template.change': 'What to change',
        'review.period.week': 'Week',
        'review.period.month': 'Month',
        'review.period.quarter': 'Quarter',
        'review.period.year': 'Year',
        'review.quarterShort': 'Q',
        'review.title.week': 'Week {week} · {from} – {to}',
        'review.week.open': 'Week {week} — open its note',
        'review.section.tasks': 'Tasks',
        'review.section.habits': 'Habits',
        'review.section.content': 'Read and watched',
        'review.section.prayer': 'Prayer',
        'review.section.fasting': 'Fasting',
        'review.section.words': 'Journal',
        'review.tasks.done.one': '{count} task done',
        'review.tasks.done.other': '{count} tasks done',
        'review.tasks.cancelled.one': '{count} given up',
        'review.tasks.cancelled.other': '{count} given up',
        'review.tasks.open.one': '{count} still due',
        'review.tasks.open.other': '{count} still due',
        'review.habit': '{name}: {kept} of {days}',
        'review.habit.run.one': 'best run {count} day',
        'review.habit.run.other': 'best run {count} days',
        'review.content.finished.one': '{count} finished',
        'review.content.finished.other': '{count} finished',
        'review.content.started.one': '{count} started',
        'review.content.started.other': '{count} started',
        'review.prayer': '{percent}% on time · {late} late · {missed} missed',
        'review.words': '{words} words over {days}',
        'review.days.one': '{count} day',
        'review.days.other': '{count} days',
        'review.empty': 'Nothing recorded in this period yet.',
        'review.freeze': 'Freeze',
        'review.freeze.hint': 'Write these numbers into the note below the block, as they are now.',
        'review.frozenShort': 'Frozen',
        'review.frozen': 'Frozen on {date}',
        'review.markReviewed': 'Mark reviewed',
        'review.reviewed': 'Reviewed',
        'review.year.open': 'Year in review',
        'review.year.title': 'Year in review',
        'review.year.notYet': 'The year in review opens on 1 December.',
        'review.year.prev': 'Previous year',
        'review.year.next': 'Next year',
        'review.year.tasks': 'tasks done',
        'review.year.words': 'words in the journal, over {days}',
        'review.year.content': 'books, films and shows finished',
        'review.year.bestRun': 'longest run: {name}',
        'review.year.prayer': 'of prayers on time',
        'review.year.fasting': 'days of Ramadan fasted',
        'review.year.challenge': '{type}: {done} of {target}',
        'review.year.mood': 'Mood by month',
        'review.year.image': 'Picture to share',
        'review.year.saveImage': 'Save picture',
        'review.year.imageFailed': 'Could not save the picture.',
        'settings.reviews': 'Review notes',
        'settings.reviews.desc':
            'Folder (empty: the journal’s), name pattern and template for each period’s note. Patterns take YYYY, MM, Q, GGGG and WW. Created only when you open one.',
        'settings.reviews.folder': 'Folder',
        'settings.reviews.format': 'Name pattern',
        'settings.reviews.template': 'Template note',
        'settings.reviews.periodicNotes':
            'Periodic Notes is on too. Its weekly and monthly notes and Zenith’s are two separate sets — point one at the other’s folder and pattern, or use only one.',
    },
    ru: {
        'feature.journal.goals': 'Цели на неделю и пределы',
        'feature.journal.goals.desc':
            '«Три раза в неделю», «не больше двух кофе» и дни отдыха (`sport: rest`), которые не рвут серию и не продлевают её.',
        'feature.journal.quitHabits': 'Привычки «бросить»',
        'feature.journal.quitHabits.desc':
            'Трекер для того, от чего отказываетесь, считается по записанным дням: «12 из 15 записанных дней без него».',

        'settings.journalTrackers.period': 'Цель',
        'settings.journalTrackers.period.day': 'Каждый день',
        'settings.journalTrackers.period.week': 'Дней в неделю',
        'settings.journalTrackers.count': 'Дней',
        'settings.journalTrackers.direction': 'Цель —',
        'settings.journalTrackers.direction.atLeast': 'не меньше',
        'settings.journalTrackers.direction.atMost': 'не больше',
        'settings.journalTrackers.mode': 'Привычка',
        'settings.journalTrackers.mode.build': 'Завести',
        'settings.journalTrackers.mode.quit': 'Бросить',
        'settings.journalTrackers.goalKept':
            'Дни до сегодняшнего остаются при прежней цели — её смена не переписывает прошлое.',

        'journal.quit.basis': '{kept} из {recorded} записанных дней без «{label}»',
        'journal.goals.weekBasis.one': 'эта неделя · {count} неделя подряд',
        'journal.goals.weekBasis.few': 'эта неделя · {count} недели подряд',
        'journal.goals.weekBasis.many': 'эта неделя · {count} недель подряд',
        'habits.rest': 'День отдыха',

        'feature.journal.yearPixels': 'Год в пикселях',
        'feature.journal.yearPixels.desc':
            'Весь год квадратиками, по одному на день, в цвет настроения или другого трекера.',
        'journal.year.open': 'Год в пикселях',
        'journal.year.month': 'Назад к месяцу',
        'journal.year.prev': 'Предыдущий год',
        'journal.year.next': 'Следующий год',
        'journal.year.this': 'Этот год',
        'journal.year.by': 'Цвет по',
        'journal.year.neutral': 'Серое — ничего не записано',

        'feature.journal.dailyPrompt': 'Вопрос дня',
        'feature.journal.dailyPrompt.desc':
            'Один вопрос в день в блоке отметок и в шаблоне как {{prompt}}. В заметку пишется только по вашей просьбе.',
        'settings.journalPrompt': 'Вопросы',
        'settings.journalPrompt.desc':
            'Заметка с вопросами, по одному в строке. Пусто — небольшой встроенный набор на языке интерфейса.',
        'settings.journalPrompt.placeholder': 'Шаблоны/Вопросы.md',
        'journal.prompt.insert': 'Записать в заметку',

        'feature.journal.rituals': 'Ритуалы утра и вечера',
        'feature.journal.rituals.desc':
            'Короткий взгляд на день утром и на сделанное вечером. Команды, карточка на дашборде и напоминания, если нужны.',
        'widget.ritual': 'Ритуал',
        'ritual.off': 'Zenith: ритуалы выключены (Дневник → Функции).',
        'ritual.morning.title': 'Утро',
        'ritual.evening.title': 'Итог дня',
        'ritual.morning.remind': 'Взгляд на день впереди.',
        'ritual.evening.remind': 'Взгляд на прошедший день.',
        'ritual.morning.today': 'Сегодня',
        'ritual.morning.overdue': 'Осталось с прошлых дней',
        'ritual.evening.done': 'Сделано сегодня',
        'ritual.evening.open': 'Не сделано',
        'ritual.evening.tomorrow': 'На завтра',
        'ritual.focus.pick': 'Главное на сегодня',
        'ritual.focus.is': 'Главное: {title}',
        'ritual.done': 'Сделано',
        'ritual.today': 'Сегодня',
        'ritual.postpone': 'Завтра',
        'ritual.cancel': 'Отменить',
        'ritual.failed': 'Zenith: эта задача изменилась в заметке — откройте, чтобы посмотреть.',
        'ritual.empty.today': 'На сегодня ничего не запланировано.',
        'ritual.empty.overdue': 'Ничего не осталось.',
        'ritual.empty.done': 'Сегодня ничего не отмечено — и так бывает.',
        'ritual.empty.open': 'Ничего не осталось открытым.',
        'ritual.tomorrow.label': 'На завтра:',
        'ritual.tomorrow.placeholder': 'Одна строка на утро…',
        'ritual.tomorrow.save': 'Записать в заметку дня',
        'ritual.tomorrow.saved': 'Записано в заметку дня.',
        'ritual.close': 'Закрыть',
        'ritual.card.open': 'Открыть',
        'ritual.card.tasks.one': '{count} задача на сегодня',
        'ritual.card.tasks.few': '{count} задачи на сегодня',
        'ritual.card.tasks.many': '{count} задач на сегодня',
        'settings.ritual': 'Ритуалы',
        'settings.ritual.morning': 'Утро в',
        'settings.ritual.evening': 'Вечер в',
        'settings.ritual.reminders': 'Напоминать',
        'settings.ritual.reminders.desc':
            'В эти часы, в центре уведомлений. Ритуал, пропущенный пока Obsidian был закрыт, не сохраняется.',
        'settings.ritual.steps': 'Шаги',
        'ritual.step.morning.today': 'Утро: задачи на сегодня',
        'ritual.step.morning.focus': 'Утро: главное',
        'ritual.step.morning.overdue': 'Утро: оставшееся',
        'ritual.step.evening.done': 'Вечер: сделано',
        'ritual.step.evening.open': 'Вечер: не сделано',
        'ritual.step.evening.tomorrow': 'Вечер: строка на завтра',
        'feature.journal.reviews': 'Обзоры',
        'feature.journal.reviews.desc':
            'Заметки недели, месяца, квартала и года с блоком zenith-summary: он считает период живьём и по кнопке фиксирует итог в заметке.',
        'feature.journal.yearInReview': 'Итоги года',
        'feature.journal.yearInReview.desc':
            'Год, прочитанный из ваших заметок: задачи, привычки, настроение, слова, прочитанное, намазы и пост. С 1 декабря — и за любой прошлый год.',
        'review.off': 'Обзоры выключены (Дневник → Функции).',
        'review.error.create':
            'Не удалось создать заметку обзора — проверьте папку и шаблон имени в настройках дневника.',
        'review.template.well': 'Что получилось',
        'review.template.change': 'Что изменить',
        'review.period.week': 'Неделя',
        'review.period.month': 'Месяц',
        'review.period.quarter': 'Квартал',
        'review.period.year': 'Год',
        'review.quarterShort': 'Кв. ',
        'review.title.week': 'Неделя {week} · {from} – {to}',
        'review.week.open': 'Неделя {week} — открыть её заметку',
        'review.section.tasks': 'Задачи',
        'review.section.habits': 'Привычки',
        'review.section.content': 'Прочитано и просмотрено',
        'review.section.prayer': 'Намаз',
        'review.section.fasting': 'Пост',
        'review.section.words': 'Дневник',
        'review.tasks.done.one': 'выполнена {count} задача',
        'review.tasks.done.few': 'выполнено {count} задачи',
        'review.tasks.done.many': 'выполнено {count} задач',
        'review.tasks.cancelled.one': '{count} отменена',
        'review.tasks.cancelled.few': '{count} отменены',
        'review.tasks.cancelled.many': '{count} отменено',
        'review.tasks.open.one': '{count} ещё в сроке',
        'review.tasks.open.few': '{count} ещё в сроке',
        'review.tasks.open.many': '{count} ещё в сроке',
        'review.habit': '{name}: {kept} из {days}',
        'review.habit.run.one': 'лучшая серия {count} день',
        'review.habit.run.few': 'лучшая серия {count} дня',
        'review.habit.run.many': 'лучшая серия {count} дней',
        'review.content.finished.one': 'закончено {count}',
        'review.content.finished.few': 'закончено {count}',
        'review.content.finished.many': 'закончено {count}',
        'review.content.started.one': 'начато {count}',
        'review.content.started.few': 'начато {count}',
        'review.content.started.many': 'начато {count}',
        'review.prayer': '{percent}% вовремя · {late} с опозданием · {missed} пропущено',
        'review.words': '{words} слов за {days}',
        'review.days.one': '{count} день',
        'review.days.few': '{count} дня',
        'review.days.many': '{count} дней',
        'review.empty': 'За этот период пока ничего не записано.',
        'review.freeze': 'Зафиксировать',
        'review.freeze.hint': 'Записать эти числа в заметку под блоком — такими, какие они сейчас.',
        'review.frozenShort': 'Зафиксировано',
        'review.frozen': 'Зафиксировано {date}',
        'review.markReviewed': 'Отметить просмотренным',
        'review.reviewed': 'Просмотрено',
        'review.year.open': 'Итоги года',
        'review.year.title': 'Итоги года',
        'review.year.notYet': 'Итоги года открываются 1 декабря.',
        'review.year.prev': 'Предыдущий год',
        'review.year.next': 'Следующий год',
        'review.year.tasks': 'задач выполнено',
        'review.year.words': 'слов в дневнике, за {days}',
        'review.year.content': 'книг, фильмов и сериалов закончено',
        'review.year.bestRun': 'самая длинная серия: {name}',
        'review.year.prayer': 'намазов вовремя',
        'review.year.fasting': 'дней Рамадана в посту',
        'review.year.challenge': '{type}: {done} из {target}',
        'review.year.mood': 'Настроение по месяцам',
        'review.year.image': 'Картинка, чтобы поделиться',
        'review.year.saveImage': 'Сохранить картинку',
        'review.year.imageFailed': 'Не удалось сохранить картинку.',
        'settings.reviews': 'Заметки обзоров',
        'settings.reviews.desc':
            'Папка (пусто — папка дневника), шаблон имени и шаблон заметки для каждого периода. В именах работают YYYY, MM, Q, GGGG и WW. Заметка создаётся, только когда вы её открываете.',
        'settings.reviews.folder': 'Папка',
        'settings.reviews.format': 'Шаблон имени',
        'settings.reviews.template': 'Заметка-шаблон',
        'settings.reviews.periodicNotes':
            'Включён и Periodic Notes. Его заметки недели и месяца и заметки Zenith — два разных комплекта: направьте один на папку и шаблон другого или пользуйтесь одним.',
    },
};
