/** The notification center's words, merged into the dictionary in `i18n.ts`. */
export const NOTIFY_STRINGS: { en: Record<string, string>; ru: Record<string, string> } = {
    en: {
        'settings.notifications': 'Notifications',
        'settings.notifications.desc': 'Reminders, quiet hours and the notification center',
        'settings.notify.delivery': 'How they reach you',
        'settings.notify.delivery.desc':
            'Reminders appear while Obsidian is open. On a phone they can only appear inside Obsidian — a plugin cannot use the phone’s notifications. Whatever you miss waits in the center.',
        'settings.notifySystem': 'System notifications',
        'settings.notifySystem.desc':
            'Also show the computer’s own notification, so it reaches you in another window. On this device only.',
        'settings.notifyQuietFrom': 'Quiet hours from',
        'settings.notifyQuietFrom.desc':
            'Nothing pops up in these hours; reminders wait in the center instead.',
        'settings.notifyQuietTo': 'Quiet hours until',
        'settings.notifyQuiet.off': 'Off',
        'settings.notifyMuted': 'Only in the center',
        'settings.notifyMuted.desc': 'These never pop up, and are still recorded.',

        'notify.title': 'Notifications',
        'notify.empty': 'Nothing here yet.',
        'notify.today': 'Today',
        'notify.earlier': 'Earlier',
        'notify.missed': 'missed',
        'notify.open': 'Open',
        'notify.complete': 'Mark done',
        'notify.completeFailed': 'Could not mark it done — the note may have changed.',
        'notify.snooze': 'Remind me later',
        'notify.snooze.10m': 'In 10 minutes',
        'notify.snooze.1h': 'In an hour',
        'notify.snooze.tomorrow': 'Tomorrow',
        'notify.dismiss': 'Remove',
        'notify.markAllRead': 'Mark all read',
        'notify.clearRead': 'Clear read',
        'notify.source.prayer': 'Prayer reminders',
        'notify.source.tasks': 'Task reminders',
        'notify.source.rituals': 'Morning and evening rituals',
        'notify.source.debug': 'Debug tests',

        'prayer.notice.at': '{prayer} — {time}',

        'debug.tab.notify': 'Notifications',
        'debug.notify.compose': 'Test notification',
        'debug.notify.title': 'Title',
        'debug.notify.body': 'Text',
        'debug.notify.defaultTitle': 'Test notification',
        'debug.notify.defaultBody': 'Sent from the debug page.',
        'debug.notify.opens': 'Opens',
        'debug.notify.opens.none': 'Nothing',
        'debug.notify.opens.tasks': 'Tasks',
        'debug.notify.opens.prayer': 'Prayer times',
        'debug.notify.completable': 'Can be marked done',
        'debug.notify.now': 'Send now',
        'debug.notify.missed': 'Send as missed',
        'debug.notify.in10s': 'In 10 seconds',
        'debug.notify.in1m': 'In a minute',
        'debug.notify.scheduled': 'Scheduled in {seconds} s, through the real scheduler.',
        'debug.notify.hint':
            'Tests follow the real rules: quiet hours, sources kept silent and a switched-off center all apply. Sent as missed, a test goes into the center without popping up.',
        'debug.notify.state': 'State',
        'debug.notify.center': 'Center',
        'debug.notify.records': 'Records',
        'debug.notify.recordsValue': '{count}, unread {unread}',
        'debug.notify.watermark': 'Handled up to',
        'debug.notify.sources': 'Sources',
        'debug.notify.pending': 'Scheduled tests',
        'debug.notify.pendingValue': '{count}, next in {seconds} s',
        'debug.notify.quiet': 'Quiet hours now',
        'debug.notify.muted': 'Only in the center',
        'debug.notify.system': 'System notifications',
        'debug.notify.systemMobile': 'not on a phone',
        'debug.notify.on': 'on',
        'debug.notify.off': 'off',
        'debug.notify.yes': 'yes',
        'debug.notify.no': 'no',
        'debug.notify.openCenter': 'Open the center',
        'debug.notify.askPermission': 'Ask for system permission',
        'debug.notify.clear': 'Clear all records',
    },
    ru: {
        'settings.notifications': 'Уведомления',
        'settings.notifications.desc': 'Напоминания, тихие часы и центр уведомлений',
        'settings.notify.delivery': 'Как они до вас доходят',
        'settings.notify.delivery.desc':
            'Напоминания появляются, пока Obsidian открыт. На телефоне — только внутри Obsidian: плагину недоступны уведомления телефона. Всё пропущенное ждёт в центре.',
        'settings.notifySystem': 'Системные уведомления',
        'settings.notifySystem.desc':
            'Показывать и уведомление самого компьютера, чтобы оно дошло и в другом окне. Только на этом устройстве.',
        'settings.notifyQuietFrom': 'Тихие часы с',
        'settings.notifyQuietFrom.desc':
            'В эти часы ничего не всплывает — напоминания ждут в центре.',
        'settings.notifyQuietTo': 'Тихие часы до',
        'settings.notifyQuiet.off': 'Выключены',
        'settings.notifyMuted': 'Только в центре',
        'settings.notifyMuted.desc': 'Эти не всплывают, но записываются.',

        'notify.title': 'Уведомления',
        'notify.empty': 'Пока пусто.',
        'notify.today': 'Сегодня',
        'notify.earlier': 'Раньше',
        'notify.missed': 'пропущено',
        'notify.open': 'Открыть',
        'notify.complete': 'Отметить выполненным',
        'notify.completeFailed': 'Не удалось отметить — возможно, заметка изменилась.',
        'notify.snooze': 'Напомнить позже',
        'notify.snooze.10m': 'Через 10 минут',
        'notify.snooze.1h': 'Через час',
        'notify.snooze.tomorrow': 'Завтра',
        'notify.dismiss': 'Убрать',
        'notify.markAllRead': 'Прочитать все',
        'notify.clearRead': 'Убрать прочитанные',
        'notify.source.prayer': 'Напоминания о намазе',
        'notify.source.tasks': 'Напоминания о задачах',
        'notify.source.rituals': 'Ритуалы утра и вечера',
        'notify.source.debug': 'Тесты отладки',

        'prayer.notice.at': '{prayer} — {time}',

        'debug.tab.notify': 'Уведомления',
        'debug.notify.compose': 'Тестовое уведомление',
        'debug.notify.title': 'Заголовок',
        'debug.notify.body': 'Текст',
        'debug.notify.defaultTitle': 'Тестовое уведомление',
        'debug.notify.defaultBody': 'Отправлено со страницы отладки.',
        'debug.notify.opens': 'Открывает',
        'debug.notify.opens.none': 'Ничего',
        'debug.notify.opens.tasks': 'Задачи',
        'debug.notify.opens.prayer': 'Время намаза',
        'debug.notify.completable': 'Можно отметить выполненным',
        'debug.notify.now': 'Отправить сейчас',
        'debug.notify.missed': 'Как пропущенное',
        'debug.notify.in10s': 'Через 10 секунд',
        'debug.notify.in1m': 'Через минуту',
        'debug.notify.scheduled': 'Запланировано через {seconds} с, через настоящий планировщик.',
        'debug.notify.hint':
            'Тесты подчиняются настоящим правилам: тихие часы, беззвучные источники и выключенный центр действуют. Отправленное как пропущенное попадает в центр, не всплывая.',
        'debug.notify.state': 'Состояние',
        'debug.notify.center': 'Центр',
        'debug.notify.records': 'Записи',
        'debug.notify.recordsValue': '{count}, непрочитанных {unread}',
        'debug.notify.watermark': 'Обработано до',
        'debug.notify.sources': 'Источники',
        'debug.notify.pending': 'Запланированные тесты',
        'debug.notify.pendingValue': '{count}, ближайший через {seconds} с',
        'debug.notify.quiet': 'Сейчас тихие часы',
        'debug.notify.muted': 'Только в центре',
        'debug.notify.system': 'Системные уведомления',
        'debug.notify.systemMobile': 'не на телефоне',
        'debug.notify.on': 'включён',
        'debug.notify.off': 'выключен',
        'debug.notify.yes': 'да',
        'debug.notify.no': 'нет',
        'debug.notify.openCenter': 'Открыть центр',
        'debug.notify.askPermission': 'Запросить разрешение системы',
        'debug.notify.clear': 'Очистить все записи',
    },
};
