/** The profiles' words, merged into the dictionary in `i18n.ts`. */
export const PROFILE_STRINGS: { en: Record<string, string>; ru: Record<string, string> } = {
    en: {
        'settings.profiles': 'Profiles',
        'settings.profiles.desc': 'Templates, your own setups, export and import',

        'profiles.templates': 'Templates',
        'profiles.template.minimum': 'Minimum',
        'profiles.template.minimum.desc': 'Dashboard, tasks and a journal — nothing extra.',
        'profiles.template.everything': 'Everything',
        'profiles.template.everything.desc': 'Every module, every feature.',
        'profiles.template.habits': 'Habits and journal',
        'profiles.template.habits.desc': 'A journal with every tracker view, and tasks in their simplest form.',
        'profiles.template.planning': 'Tasks and planning',
        'profiles.template.planning.desc': 'Tasks, calendar and projects with all their tools.',
        'profiles.template.prayer': 'Prayer and fasting',
        'profiles.template.prayer.desc': 'Prayer times, reminders and tracking, with a minimal journal to record them in.',
        'profiles.template.reading': 'Reading and media',
        'profiles.template.reading.desc': 'The content library with all its tools.',

        'profiles.mine': 'Your profiles',
        'profiles.mine.empty': 'None yet.',
        'profiles.before': 'Before profiles',
        'profiles.review': 'Review…',
        'profiles.more': 'More',
        'profiles.save': 'Save the current setup',
        'profiles.save.desc': 'Modules, features and settings as they are now, under a name.',
        'profiles.save.button': 'Save…',
        'profiles.namePlaceholder': 'My setup',
        'profiles.saved': 'Saved “{name}”.',
        'profiles.rename': 'Rename',
        'profiles.export': 'Export…',
        'profiles.delete.confirm': 'Delete “{name}”?',

        'profiles.undo': 'Last applied: “{name}”',
        'profiles.undo.button': 'Put it back',
        'profiles.undone': 'Put back as it was.',

        'profiles.preview.title': 'Apply “{name}”',
        'profiles.apply': 'Apply',
        'profiles.applied': 'Applied “{name}”. Settings → Profiles can put it back.',
        'profiles.mode.replace': 'Replace',
        'profiles.mode.add': 'Add to current',
        'profiles.mode.replace.desc':
            'Everything the profile speaks for becomes as it says; what it does not mention stays.',
        'profiles.mode.add.desc':
            'Only switches things on — modules and features the profile has on. Nothing is switched off, no setting changes.',
        'profiles.preview.nothing': 'Nothing would change.',
        'profiles.preview.on': 'Switched on:',
        'profiles.preview.off': 'Switched off:',
        'profiles.preview.settings.one': 'and {count} setting changes',
        'profiles.preview.settings.other': 'and {count} settings change',
        'profiles.preview.undo': 'Whatever changes can be put back in Settings → Profiles.',
        'profiles.report.modules': 'Not installed, so left out: {list}',
        'profiles.report.skipped': 'Not understood by this version, so left out: {list}',

        'profiles.import': 'Import',
        'profiles.import.file': 'From a file',
        'profiles.import.file.desc': 'A profile saved in this vault.',
        'profiles.import.choose': 'Choose…',
        'profiles.import.paste': 'Paste a profile',
        'profiles.import.paste.desc': 'What “Copy” gave you on another device, or someone sent you.',
        'profiles.import.pasteButton': 'Paste…',
        'profiles.import.fromClipboard': 'From clipboard',
        'profiles.import.clipboardFailed': 'Could not read the clipboard — paste into the box instead.',
        'profiles.import.unnamed': 'Imported profile',
        'profiles.import.error.json': 'That is not JSON.',
        'profiles.import.error.format': 'That is not a Zenith profile.',
        'profiles.import.error.version': 'That profile is from a newer Zenith. Update the plugin to use it.',

        'profiles.export.title': 'Export “{name}”',
        'profiles.export.paths': 'Include folders',
        'profiles.export.paths.desc': 'Someone else’s vault has other folders.',
        'profiles.export.place': 'Include location',
        'profiles.export.place.desc': 'Where you are, for weather and prayer times.',
        'profiles.export.never':
            'Passwords, tokens and server settings are never exported.',
        'profiles.export.copy': 'Copy',
        'profiles.export.copied': 'Copied.',
        'profiles.export.copyFailed': 'Could not copy — export to a file instead.',
        'profiles.export.file': 'Save to vault',
        'profiles.export.written': 'Saved to {path}.',

        'profiles.firstRun.title': 'How will you use Zenith?',
        'profiles.firstRun.lead':
            'Pick a starting point. Everything can be switched on or off later, and Settings → Profiles can put it back.',
        'profiles.firstRun.keep': 'Keep everything as it is',
        'profiles.firstRun.done': '“{name}” is set up. Change it any time in Settings → Profiles.',
    },
    ru: {
        'settings.profiles': 'Профили',
        'settings.profiles.desc': 'Шаблоны, свои наборы, экспорт и импорт',

        'profiles.templates': 'Шаблоны',
        'profiles.template.minimum': 'Минимум',
        'profiles.template.minimum.desc': 'Дашборд, задачи и дневник — без дополнений.',
        'profiles.template.everything': 'Всё',
        'profiles.template.everything.desc': 'Все модули и все функции.',
        'profiles.template.habits': 'Привычки и дневник',
        'profiles.template.habits.desc': 'Дневник со всеми видами трекеров и задачи в самом простом виде.',
        'profiles.template.planning': 'Задачи и планирование',
        'profiles.template.planning.desc': 'Задачи, календарь и проекты со всеми инструментами.',
        'profiles.template.prayer': 'Намаз и пост',
        'profiles.template.prayer.desc': 'Время намаза, напоминания и отметки — и дневник в минимуме, чтобы их записывать.',
        'profiles.template.reading': 'Чтение и медиа',
        'profiles.template.reading.desc': 'Библиотека контента со всеми инструментами.',

        'profiles.mine': 'Ваши профили',
        'profiles.mine.empty': 'Пока нет.',
        'profiles.before': 'До профилей',
        'profiles.review': 'Посмотреть…',
        'profiles.more': 'Ещё',
        'profiles.save': 'Сохранить текущий набор',
        'profiles.save.desc': 'Модули, функции и настройки как сейчас — под именем.',
        'profiles.save.button': 'Сохранить…',
        'profiles.namePlaceholder': 'Мой набор',
        'profiles.saved': '«{name}» сохранён.',
        'profiles.rename': 'Переименовать',
        'profiles.export': 'Экспорт…',
        'profiles.delete.confirm': 'Удалить «{name}»?',

        'profiles.undo': 'Последний применённый: «{name}»',
        'profiles.undo.button': 'Вернуть как было',
        'profiles.undone': 'Возвращено как было.',

        'profiles.preview.title': 'Применить «{name}»',
        'profiles.apply': 'Применить',
        'profiles.applied': '«{name}» применён. Вернуть можно в Настройки → Профили.',
        'profiles.mode.replace': 'Заменить',
        'profiles.mode.add': 'Добавить к текущему',
        'profiles.mode.replace.desc':
            'Всё, о чём говорит профиль, станет как в нём; то, чего он не касается, останется.',
        'profiles.mode.add.desc':
            'Только включает — модули и функции, включённые в профиле. Ничего не выключается, настройки не меняются.',
        'profiles.preview.nothing': 'Ничего не изменится.',
        'profiles.preview.on': 'Включится:',
        'profiles.preview.off': 'Выключится:',
        'profiles.preview.settings.one': 'и изменится {count} настройка',
        'profiles.preview.settings.few': 'и изменятся {count} настройки',
        'profiles.preview.settings.many': 'и изменятся {count} настроек',
        'profiles.preview.undo': 'Всё изменённое можно вернуть в Настройки → Профили.',
        'profiles.report.modules': 'Не установлены, поэтому пропущены: {list}',
        'profiles.report.skipped': 'Эта версия их не знает, поэтому пропущены: {list}',

        'profiles.import': 'Импорт',
        'profiles.import.file': 'Из файла',
        'profiles.import.file.desc': 'Профиль, сохранённый в этом хранилище.',
        'profiles.import.choose': 'Выбрать…',
        'profiles.import.paste': 'Вставить профиль',
        'profiles.import.paste.desc': 'То, что дала кнопка «Копировать» на другом устройстве или что вам прислали.',
        'profiles.import.pasteButton': 'Вставить…',
        'profiles.import.fromClipboard': 'Из буфера',
        'profiles.import.clipboardFailed': 'Не удалось прочитать буфер — вставьте в поле вручную.',
        'profiles.import.unnamed': 'Импортированный профиль',
        'profiles.import.error.json': 'Это не JSON.',
        'profiles.import.error.format': 'Это не профиль Zenith.',
        'profiles.import.error.version': 'Профиль из более новой версии Zenith. Обновите плагин.',

        'profiles.export.title': 'Экспорт «{name}»',
        'profiles.export.paths': 'Включить папки',
        'profiles.export.paths.desc': 'У другого человека в хранилище другие папки.',
        'profiles.export.place': 'Включить местоположение',
        'profiles.export.place.desc': 'Где вы находитесь — для погоды и времени намаза.',
        'profiles.export.never':
            'Пароли, токены и настройки сервера не экспортируются никогда.',
        'profiles.export.copy': 'Копировать',
        'profiles.export.copied': 'Скопировано.',
        'profiles.export.copyFailed': 'Не удалось скопировать — сохраните в файл.',
        'profiles.export.file': 'Сохранить в хранилище',
        'profiles.export.written': 'Сохранено в {path}.',

        'profiles.firstRun.title': 'Как вы будете пользоваться Zenith?',
        'profiles.firstRun.lead':
            'Выберите, с чего начать. Всё можно включить или выключить потом, а Настройки → Профили умеют вернуть как было.',
        'profiles.firstRun.keep': 'Оставить всё как есть',
        'profiles.firstRun.done': '«{name}» настроен. Поменять можно в любой момент в Настройки → Профили.',
    },
};
