/**
 * Study strings, merged into the dictionary in `core/i18n.ts`. The module's
 * name and description are in its own chunk, `i18n.ts`.
 */
export const STUDY_STRINGS: { en: Record<string, string>; ru: Record<string, string> } = {
    en: {
        'nav.study': 'Study',
        'nav.study.desc': 'Class timetable',
        'widget.study': 'Classes',

        'feature.study.widget': 'Classes widget',
        'feature.study.widget.desc': 'What is on now and next, the day at a glance and the week.',
        'feature.study.reminders': 'Class reminders',
        'feature.study.reminders.desc': 'A notification before each class, with the room.',
        'feature.calendar.classes': 'Classes on the hour grid',
        'feature.calendar.classes.desc':
            'Your timetable, faint behind the week and day views, to plan the hours around it.',
        'feature.study.homework': 'Tasks for the next class',
        'feature.study.homework.desc':
            'In a lesson’s card: add a task due on the day the subject is next taught.',

        'study.title': 'Study',
        'study.weekLessons.one': '{count} class this week',
        'study.weekLessons.other': '{count} classes this week',
        'study.import': 'Paste a timetable',
        'study.edit': 'Edit the timetable',
        'study.copyPrompt': 'Copy the AI prompt',
        'study.promptCopied':
            'Prompt copied. Send it to any AI chat with a photo or the text of your timetable, then paste the answer here.',
        'study.copied': 'Copied.',
        'study.openFull': 'Open the timetable',

        'study.week.number.1': '1st week',
        'study.week.number.2': '2nd week',
        'study.week.numerator.1': 'Week A',
        'study.week.numerator.2': 'Week B',
        'study.week.parity.1': 'Odd week',
        'study.week.parity.2': 'Even week',
        'study.week.every': 'Every week',
        'study.week.current': 'this week',
        'study.week.swap': 'Not this week? Swap',
        'study.weekShort.1': '1',
        'study.weekShort.2': '2',

        'study.kind.lecture': 'Lecture',
        'study.kind.practice': 'Practice',
        'study.kind.lab': 'Lab',
        'study.kind.seminar': 'Seminar',
        'study.kind.exam': 'Exam',
        'study.kind.consultation': 'Consultation',
        'study.kindOther': 'Class',

        'study.pair': 'Class {n}',
        'study.subgroup': 'Group {n}',
        'study.subgroup.all': 'Whole group',
        'study.now': 'Now',
        'study.next': 'Next',
        'study.first': 'First class',
        'study.break': 'Break · {time}',
        'study.in': 'in {time}',
        'study.left': '{time} left',
        'study.until': 'until {time}',
        'study.then': 'Then',
        'study.dayDone': 'Classes are over',
        'study.free': 'No classes today',
        'study.tomorrow': 'Tomorrow from {time}',
        'study.nextDay': '{day} from {time}',
        'study.dayCount.one': '{count} class',
        'study.dayCount.other': '{count} classes',
        'study.noneAhead': 'Nothing in the next two weeks',
        'study.termBefore': 'The term starts on {date}',
        'study.termAfter': 'The term is over',
        'study.holiday': 'Holidays',
        'study.today': 'Today',
        'study.list.tomorrow': 'Tomorrow',
        'study.todayUntil': 'until {time}',
        'study.bells': 'Bells',
        'study.otherTime': 'Other times',
        'study.noClasses': 'No classes',

        'study.empty.title': 'Add your timetable',
        'study.empty.body':
            'Paste it as text — an AI chat can make that from a photo in a minute — or fill it in by hand.',

        'study.lesson.next': 'Next class: {date}',
        'study.lesson.homework': 'Task for the next class',
        'study.lesson.homeworkPrompt': 'What is due for {subject}?',
        'study.lesson.homeworkAdded': 'Task added for {date}.',
        'study.lesson.homeworkNone': 'This subject is not on the timetable in the next four weeks.',
        'study.lesson.delete': 'Delete the class',
        'study.lesson.deleteConfirm': 'Delete “{subject}” from the timetable?',
        'study.lesson.edit': 'Edit',

        'study.importTitle': 'Paste a timetable',
        'study.jsonTitle': 'Timetable as JSON',
        'study.importHelp':
            'Paste the timetable as JSON. To skip writing it yourself: copy the prompt, send it to any AI chat with a photo or the text of your classes and bell times, and paste its answer here.',
        'study.importPlaceholder': '{ "bells": […], "lessons": […] }',
        'study.exportCurrent': 'Copy the current one',
        'study.importReplace': 'Replace the timetable',
        'study.importConfirm': 'Replace the current timetable ({count} classes) with this one?',
        'study.importDone': 'Timetable saved: {count} classes.',
        'study.preview': '{bells} bells · {lessons} classes',
        'study.preview.twoWeeks': 'two-week cycle',
        'study.problem.not-json': 'This is not JSON: {detail}',
        'study.problem.no-lessons': 'No classes found.',
        'study.problem.no-day': 'Class {n}: no day — skipped.',
        'study.problem.no-subject': 'Class {n}: no subject — skipped.',
        'study.problem.no-time': 'Class {n}: no bell or times — skipped.',
        'study.problem.bad-week': 'Class {n}: unknown week — skipped.',

        'study.editorTitle': 'Edit the timetable',
        'study.tab.lessons': 'Classes',
        'study.tab.bells': 'Bells',
        'study.twoWeeks': 'Two-week timetable',
        'study.twoWeeks.desc': 'Classes that alternate between a first and a second week.',
        'study.thisWeekIs': 'This week is',
        'study.addLesson': 'Add a class',
        'study.addBell': 'Add a bell',
        'study.duplicateToOther': 'Copy to the other week',
        'study.deleteLesson': 'Delete',
        'study.generate': 'Lay out bells',
        'study.generate.first': 'First starts',
        'study.generate.length': 'Minutes',
        'study.generate.gap': 'Break',
        'study.generate.count': 'Classes',
        'study.generate.long': 'Long break after',
        'study.generate.longGap': 'minutes',
        'study.generate.apply': 'Fill in',
        'study.noBells': 'No bells yet. Add them one by one, or lay them out evenly below.',
        'study.noLessonsDay': 'Nothing on this day.',
        'study.conflicts.one': '{count} clash in the timetable',
        'study.conflicts.other': '{count} clashes in the timetable',
        'study.untimed.one': '{count} class has no time',
        'study.untimed.other': '{count} classes have no time',
        'study.save': 'Save',
        'study.cancel': 'Cancel',

        'study.field.subject': 'Subject',
        'study.field.kind': 'Kind',
        'study.field.day': 'Day',
        'study.field.time': 'Time',
        'study.field.customTime': 'Own time',
        'study.field.start': 'Start',
        'study.field.end': 'End',
        'study.field.week': 'Week',
        'study.field.subgroup': 'Subgroup',
        'study.field.room': 'Room',
        'study.field.teacher': 'Teacher',
        'study.field.note': 'Note',

        'settings.studyGroup.schedule': 'Timetable',
        'settings.studyGroup.weeks': 'Weeks',
        'settings.studyGroup.term': 'Term',
        'settings.studyGroup.reminders': 'Reminders',
        'settings.studyImport': 'Paste a timetable',
        'settings.studyImport.desc': 'From JSON — for example, what an AI chat made from a photo.',
        'settings.studyImport.button': 'Paste',
        'settings.studyEdit': 'Edit by hand',
        'settings.studyEdit.desc': 'Classes, bells and weeks, one by one.',
        'settings.studyEdit.button': 'Edit',
        'settings.studyJson': 'Edit as JSON',
        'settings.studyJson.desc': 'The whole timetable as one text.',
        'settings.studyJson.button': 'Open',
        'settings.studyPrompt': 'AI prompt',
        'settings.studyPrompt.desc':
            'Explains the format to an AI chat, so it can turn a photo of your timetable into it.',
        'settings.studyPrompt.button': 'Copy',
        'settings.studyTwoWeeks': 'Two-week timetable',
        'settings.studyTwoWeeks.desc': 'Classes alternate between a first and a second week.',
        'settings.studyWeekNames': 'Call the weeks',
        'settings.studyWeekNames.number': '1st / 2nd',
        'settings.studyWeekNames.numerator': 'A / B',
        'settings.studyWeekNames.parity': 'Odd / even',
        'settings.studyThisWeek': 'This week is',
        'settings.studyThisWeek.desc': 'Everything else follows: the weeks alternate from here.',
        'settings.studySubgroup': 'My subgroup',
        'settings.studySubgroup.desc': '0 shows the classes of every subgroup.',
        'settings.studyTermStart': 'Term starts',
        'settings.studyTermEnd': 'Term ends',
        'settings.studyTerm.desc':
            'YYYY-MM-DD. Outside the term the timetable shows holidays. Optional.',
        'settings.studyTerm.invalid': 'Write it as YYYY-MM-DD.',
        'settings.studyRemindBefore': 'Remind before',
        'study.remind.in': 'in {minutes} min · {place}',
        'study.remind.at': 'at {time} · {place}',
        'study.remind.noRoom': 'room not set',
        'notify.source.study': 'Class reminders',
        'profiles.template.study': 'Study',
        'profiles.template.study.desc': 'Timetable, tasks and deadlines, a light journal.',
        'study.preview.badge': 'Preview time',
        'study.preview.reset': 'Back to the real time',
        'debug.tab.study': 'Study',
        'debug.study.clock': 'Time for Study',
        'debug.study.date': 'Date',
        'debug.study.time': 'Time',
        'debug.study.apply': 'Show at this time',
        'debug.study.moments': 'Moments of the day',
        'debug.study.preset.before': 'Before classes',
        'debug.study.preset.during': 'In a class',
        'debug.study.preset.break': 'Break',
        'debug.study.preset.after': 'After classes',
        'debug.study.preset.free': 'Day off',
        'debug.study.empty': 'The timetable is empty: paste or add one first.',
        'debug.study.hint':
            'Moves only what the Study card and view call now, and keeps running from there. Reminders and the rest of Obsidian keep the real time. A restart goes back to it too.',
        'debug.study.state': 'What Study sees',
        'debug.study.now': 'Now',
        'debug.study.real': 'real time',
        'debug.study.preview': 'preview time',
        'debug.study.day': 'The day',
        'debug.study.week': 'Week',
        'debug.study.dayState.free': 'no classes',
        'debug.study.dayState.before': 'before the first class',
        'debug.study.dayState.during': 'in a class',
        'debug.study.dayState.break': 'a break',
        'debug.study.dayState.after': 'classes are over',
    },
    ru: {
        'nav.study': 'Учёба',
        'nav.study.desc': 'Расписание пар',
        'widget.study': 'Пары',

        'feature.study.widget': 'Виджет пар',
        'feature.study.widget.desc': 'Что сейчас и что дальше, день целиком и неделя.',
        'feature.study.reminders': 'Напоминания о парах',
        'feature.study.reminders.desc': 'Уведомление перед каждой парой, с аудиторией.',
        'feature.calendar.classes': 'Пары на сетке часов',
        'feature.calendar.classes.desc':
            'Расписание бледным фоном в неделе и дне — чтобы планировать время между парами.',
        'feature.study.homework': 'Задания к следующей паре',
        'feature.study.homework.desc':
            'В карточке пары: добавить задачу со сроком на день, когда предмет будет в следующий раз.',

        'study.title': 'Учёба',
        'study.weekLessons.one': '{count} пара на неделе',
        'study.weekLessons.few': '{count} пары на неделе',
        'study.weekLessons.many': '{count} пар на неделе',
        'study.import': 'Вставить расписание',
        'study.edit': 'Изменить расписание',
        'study.copyPrompt': 'Скопировать промпт',
        'study.promptCopied':
            'Промпт скопирован. Отправьте его в любую нейросеть вместе с фото или текстом расписания и вставьте ответ сюда.',
        'study.copied': 'Скопировано.',
        'study.openFull': 'Открыть расписание',

        'study.week.number.1': '1-я неделя',
        'study.week.number.2': '2-я неделя',
        'study.week.numerator.1': 'Числитель',
        'study.week.numerator.2': 'Знаменатель',
        'study.week.parity.1': 'Нечётная',
        'study.week.parity.2': 'Чётная',
        'study.week.every': 'Каждую неделю',
        'study.week.current': 'сейчас',
        'study.week.swap': 'Не та неделя? Поменять',
        'study.weekShort.1': '1',
        'study.weekShort.2': '2',

        'study.kind.lecture': 'Лекция',
        'study.kind.practice': 'Практика',
        'study.kind.lab': 'Лабораторная',
        'study.kind.seminar': 'Семинар',
        'study.kind.exam': 'Экзамен',
        'study.kind.consultation': 'Консультация',
        'study.kindOther': 'Занятие',

        'study.pair': '{n} пара',
        'study.subgroup': 'п/г {n}',
        'study.subgroup.all': 'Вся группа',
        'study.now': 'Сейчас',
        'study.next': 'Далее',
        'study.first': 'Первая пара',
        'study.break': 'Перерыв · {time}',
        'study.in': 'через {time}',
        'study.left': 'ещё {time}',
        'study.until': 'до {time}',
        'study.then': 'Потом',
        'study.dayDone': 'Пары закончились',
        'study.free': 'Сегодня пар нет',
        'study.tomorrow': 'Завтра с {time}',
        'study.nextDay': '{day} с {time}',
        'study.dayCount.one': '{count} пара',
        'study.dayCount.few': '{count} пары',
        'study.dayCount.many': '{count} пар',
        'study.noneAhead': 'В ближайшие две недели пар нет',
        'study.termBefore': 'Семестр начнётся {date}',
        'study.termAfter': 'Семестр закончился',
        'study.holiday': 'Каникулы',
        'study.today': 'Сегодня',
        'study.list.tomorrow': 'Завтра',
        'study.todayUntil': 'до {time}',
        'study.bells': 'Звонки',
        'study.otherTime': 'Другое время',
        'study.noClasses': 'Нет пар',

        'study.empty.title': 'Добавьте расписание',
        'study.empty.body':
            'Вставьте его текстом — нейросеть сделает такой из фото за минуту — или заполните вручную.',

        'study.lesson.next': 'Следующее занятие: {date}',
        'study.lesson.homework': 'Задание к следующей паре',
        'study.lesson.homeworkPrompt': 'Что задали по предмету «{subject}»?',
        'study.lesson.homeworkAdded': 'Задача добавлена на {date}.',
        'study.lesson.homeworkNone': 'Этого предмета нет в расписании на ближайшие четыре недели.',
        'study.lesson.delete': 'Удалить пару',
        'study.lesson.deleteConfirm': 'Удалить «{subject}» из расписания?',
        'study.lesson.edit': 'Изменить',

        'study.importTitle': 'Вставить расписание',
        'study.jsonTitle': 'Расписание в JSON',
        'study.importHelp':
            'Вставьте расписание в формате JSON. Чтобы не писать его самому: скопируйте промпт, отправьте его в любую нейросеть вместе с фото или текстом пар и звонков и вставьте её ответ сюда.',
        'study.importPlaceholder': '{ "bells": […], "lessons": […] }',
        'study.exportCurrent': 'Скопировать текущее',
        'study.importReplace': 'Заменить расписание',
        'study.importConfirm': 'Заменить текущее расписание ({count} пар) этим?',
        'study.importDone': 'Расписание сохранено: {count} пар.',
        'study.preview': 'звонков: {bells} · пар: {lessons}',
        'study.preview.twoWeeks': 'две недели',
        'study.problem.not-json': 'Это не JSON: {detail}',
        'study.problem.no-lessons': 'Пары не найдены.',
        'study.problem.no-day': 'Пара {n}: не указан день — пропущена.',
        'study.problem.no-subject': 'Пара {n}: не указан предмет — пропущена.',
        'study.problem.no-time': 'Пара {n}: нет ни номера пары, ни времени — пропущена.',
        'study.problem.bad-week': 'Пара {n}: непонятная неделя — пропущена.',

        'study.editorTitle': 'Изменить расписание',
        'study.tab.lessons': 'Пары',
        'study.tab.bells': 'Звонки',
        'study.twoWeeks': 'Двухнедельное расписание',
        'study.twoWeeks.desc': 'Пары чередуются между первой и второй неделей.',
        'study.thisWeekIs': 'Эта неделя —',
        'study.addLesson': 'Добавить пару',
        'study.addBell': 'Добавить звонок',
        'study.duplicateToOther': 'Скопировать на другую неделю',
        'study.deleteLesson': 'Удалить',
        'study.generate': 'Расставить звонки',
        'study.generate.first': 'Начало',
        'study.generate.length': 'Минут',
        'study.generate.gap': 'Перемена',
        'study.generate.count': 'Пар',
        'study.generate.long': 'Большая перемена после',
        'study.generate.longGap': 'минут',
        'study.generate.apply': 'Заполнить',
        'study.noBells': 'Звонков пока нет. Добавьте их по одному или расставьте равномерно ниже.',
        'study.noLessonsDay': 'В этот день пар нет.',
        'study.conflicts.one': '{count} пересечение в расписании',
        'study.conflicts.few': '{count} пересечения в расписании',
        'study.conflicts.many': '{count} пересечений в расписании',
        'study.untimed.one': 'У {count} пары нет времени',
        'study.untimed.few': 'У {count} пар нет времени',
        'study.untimed.many': 'У {count} пар нет времени',
        'study.save': 'Сохранить',
        'study.cancel': 'Отмена',

        'study.field.subject': 'Предмет',
        'study.field.kind': 'Вид',
        'study.field.day': 'День',
        'study.field.time': 'Время',
        'study.field.customTime': 'Своё время',
        'study.field.start': 'Начало',
        'study.field.end': 'Конец',
        'study.field.week': 'Неделя',
        'study.field.subgroup': 'Подгруппа',
        'study.field.room': 'Аудитория',
        'study.field.teacher': 'Преподаватель',
        'study.field.note': 'Примечание',

        'settings.studyGroup.schedule': 'Расписание',
        'settings.studyGroup.weeks': 'Недели',
        'settings.studyGroup.term': 'Семестр',
        'settings.studyGroup.reminders': 'Напоминания',
        'settings.studyImport': 'Вставить расписание',
        'settings.studyImport.desc': 'Из JSON — например, того, что нейросеть сделала из фото.',
        'settings.studyImport.button': 'Вставить',
        'settings.studyEdit': 'Изменить вручную',
        'settings.studyEdit.desc': 'Пары, звонки и недели — по одной.',
        'settings.studyEdit.button': 'Изменить',
        'settings.studyJson': 'Изменить в JSON',
        'settings.studyJson.desc': 'Всё расписание одним текстом.',
        'settings.studyJson.button': 'Открыть',
        'settings.studyPrompt': 'Промпт для нейросети',
        'settings.studyPrompt.desc':
            'Объясняет нейросети формат, чтобы она превратила фото расписания в него.',
        'settings.studyPrompt.button': 'Скопировать',
        'settings.studyTwoWeeks': 'Двухнедельное расписание',
        'settings.studyTwoWeeks.desc': 'Пары чередуются между первой и второй неделей.',
        'settings.studyWeekNames': 'Называть недели',
        'settings.studyWeekNames.number': '1-я / 2-я',
        'settings.studyWeekNames.numerator': 'Числитель / знаменатель',
        'settings.studyWeekNames.parity': 'Нечётная / чётная',
        'settings.studyThisWeek': 'Эта неделя —',
        'settings.studyThisWeek.desc': 'От неё недели и чередуются дальше.',
        'settings.studySubgroup': 'Моя подгруппа',
        'settings.studySubgroup.desc': '0 — показывать пары всех подгрупп.',
        'settings.studyTermStart': 'Начало семестра',
        'settings.studyTermEnd': 'Конец семестра',
        'settings.studyTerm.desc':
            'ГГГГ-ММ-ДД. Вне семестра расписание показывает каникулы. Необязательно.',
        'settings.studyTerm.invalid': 'В формате ГГГГ-ММ-ДД.',
        'settings.studyRemindBefore': 'Напоминать за',
        'study.remind.in': 'через {minutes} мин · {place}',
        'study.remind.at': 'в {time} · {place}',
        'study.remind.noRoom': 'аудитория не указана',
        'notify.source.study': 'Напоминания о парах',
        'profiles.template.study': 'Учёба',
        'profiles.template.study.desc': 'Расписание, задачи и сроки, лёгкий дневник.',
        'study.preview.badge': 'Время для просмотра',
        'study.preview.reset': 'Вернуть настоящее время',
        'debug.tab.study': 'Учёба',
        'debug.study.clock': 'Время для «Учёбы»',
        'debug.study.date': 'Дата',
        'debug.study.time': 'Время',
        'debug.study.apply': 'Показать на это время',
        'debug.study.moments': 'Моменты дня',
        'debug.study.preset.before': 'До пар',
        'debug.study.preset.during': 'Идёт пара',
        'debug.study.preset.break': 'Перемена',
        'debug.study.preset.after': 'После пар',
        'debug.study.preset.free': 'Выходной',
        'debug.study.empty': 'Расписание пустое: сначала вставьте или добавьте его.',
        'debug.study.hint':
            'Сдвигает только «сейчас» карточки и вида «Учёбы» — дальше время идёт от него. Напоминания и остальной Obsidian живут по настоящему времени. После перезапуска тоже вернётся настоящее.',
        'debug.study.state': 'Что видит «Учёба»',
        'debug.study.now': 'Сейчас',
        'debug.study.real': 'настоящее время',
        'debug.study.preview': 'время для просмотра',
        'debug.study.day': 'День',
        'debug.study.week': 'Неделя',
        'debug.study.dayState.free': 'пар нет',
        'debug.study.dayState.before': 'до первой пары',
        'debug.study.dayState.during': 'идёт пара',
        'debug.study.dayState.break': 'перемена',
        'debug.study.dayState.after': 'пары закончились',
    },
};
