/**
 * Content strings added with re-reads and the yearly challenge, merged into the
 * dictionary in `core/i18n.ts`.
 */
export const CONTENT_STRINGS: { en: Record<string, string>; ru: Record<string, string> } = {
    en: {
        'feature.content.readings': 'Re-reads',
        'feature.content.readings.desc':
            'Starting a finished item again keeps the earlier reading, so each one counts for itself — in the history and in the reading time.',
        'content.detail.readings': 'Readings',
        'content.detail.readingOpen': 'since {date}',
        'content.detail.readingSpan': '{from} → {to}',

        'feature.content.challenge': 'Yearly challenge',
        'feature.content.challenge.desc':
            '“24 books this year”: a goal per type, with how the pace is keeping up. Card on the dashboard and in the statistics.',
        'widget.challenge': 'Challenge',
        'content.challenge.label': '{type} · {year}',
        'content.challenge.done': 'Done — well read.',
        'content.challenge.ahead': '{count} ahead of pace',
        'content.challenge.behind': '{count} behind pace',
        'content.challenge.onTrack': 'On pace',
        'content.challenge.none': 'No goal for this year yet — set one in Settings → Content.',
        'settings.contentChallenge': 'Goals for {year}',
        'settings.contentChallenge.desc':
            'How many of each type to finish this year. Empty is no goal. Next year starts empty; this year’s goals stay with this year.',
        'settings.contentChallengeRereads': 'Count re-reads',
        'settings.contentChallengeRereads.desc':
            'On: every reading finished this year counts. Off: only what is finished for the first time.',

        'content.status.backlog': 'Planned',
        'content.status.inProgress': 'In progress',
        'content.status.onHold': 'On hold',
        'content.status.completed': 'Completed',
        'content.status.dropped': 'Dropped',
        'content.status.read.inProgress': 'Reading',
        'content.status.read.completed': 'Read',
        'content.status.watch.inProgress': 'Watching',
        'content.status.watch.completed': 'Watched',
        'content.status.play.inProgress': 'Playing',
        'content.status.play.completed': 'Finished',
        'content.status.listen.inProgress': 'Listening',
        'content.status.listen.completed': 'Listened',
        'content.type.book.label': 'Book',
        'content.type.movie.label': 'Movie',
        'content.type.show.label': 'Show',
        'content.type.anime.label': 'Anime',
        'content.type.manga.label': 'Manga',
        'content.type.game.label': 'Game',
        'content.type.music.label': 'Music',
        'content.type.other.label': 'Other',
        'content.creator.book.label': 'Author',
        'content.creator.movie.label': 'Director',
        'content.creator.show.label': 'Network',
        'content.creator.anime.label': 'Studio',
        'content.creator.manga.label': 'Author',
        'content.creator.game.label': 'Developer',
        'content.creator.music.label': 'Artist',
        'content.creator.other.label': 'Creator',
        'content.unit.pages': 'pages',
        'content.unit.minutes': 'minutes',
        'content.unit.episodes': 'episodes',
        'content.unit.chapters': 'chapters',
        'content.unit.hours': 'hours',
        'content.unit.tracks': 'tracks',
        'content.unit.units': 'units',
        'content.favorite.add': 'Add to favourites',
        'content.favorite.remove': 'Remove from favourites',
        'content.favorite.filter': 'Favourites only',
        'content.layout.list': 'Show as a list',
        'content.layout.grid': 'Show as a grid',
        'content.stats.finishedByMonth': 'Finished by month',
        'content.stats.finishedYear': '{count} in the past year',
        'content.stats.avgDays': '{count} days each on average',
        'content.form.more': 'More',
        'content.form.type': 'Type',
        'content.import.new': 'New',
        'content.import.updates': 'Moved on in the export',
        'content.import.backward': 'Unticked: the export has these further back than the library. Tick one to take the export’s status anyway.',
        'content.import.same.one': '{count} already in the library as the export has it',
        'content.import.same.other': '{count} already in the library as the export has them',
        'content.import.run': 'Import {created}, update {updated}',
        'content.import.doneBoth': 'Imported {created}, updated {updated}',
        'ctypes.show': 'Show this type',
        'ctypes.hide': 'Hide this type',
    },
    ru: {
        'feature.content.readings': 'Повторные прочтения',
        'feature.content.readings.desc':
            'Если начать завершённое заново, прежнее прочтение сохраняется, и каждое считается само по себе — в истории и во времени прочтения.',
        'content.detail.readings': 'Прочтения',
        'content.detail.readingOpen': 'с {date}',
        'content.detail.readingSpan': '{from} → {to}',

        'feature.content.challenge': 'Годовой челлендж',
        'feature.content.challenge.desc':
            '«24 книги за год»: цель по каждому типу и то, успевает ли темп. Карточка на дашборде и в статистике.',
        'widget.challenge': 'Челлендж',
        'content.challenge.label': '{type} · {year}',
        'content.challenge.done': 'Готово — отлично прочитано.',
        'content.challenge.ahead': 'на {count} впереди темпа',
        'content.challenge.behind': 'на {count} позади темпа',
        'content.challenge.onTrack': 'В темпе',
        'content.challenge.none': 'Цели на этот год пока нет — задайте её в Настройки → Контент.',
        'settings.contentChallenge': 'Цели на {year}',
        'settings.contentChallenge.desc':
            'Сколько каждого типа закончить в этом году. Пусто — без цели. Следующий год начнётся пустым; цели этого года останутся при нём.',
        'settings.contentChallengeRereads': 'Считать повторы',
        'settings.contentChallengeRereads.desc':
            'Вкл.: считается каждое прочтение, законченное в этом году. Выкл.: только прочитанное впервые.',

        'content.status.backlog': 'В планах',
        'content.status.inProgress': 'В процессе',
        'content.status.onHold': 'Отложено',
        'content.status.completed': 'Завершено',
        'content.status.dropped': 'Брошено',
        'content.status.read.inProgress': 'Читаю',
        'content.status.read.completed': 'Прочитано',
        'content.status.watch.inProgress': 'Смотрю',
        'content.status.watch.completed': 'Просмотрено',
        'content.status.play.inProgress': 'Играю',
        'content.status.play.completed': 'Пройдено',
        'content.status.listen.inProgress': 'Слушаю',
        'content.status.listen.completed': 'Прослушано',
        'content.type.book.label': 'Книга',
        'content.type.movie.label': 'Фильм',
        'content.type.show.label': 'Сериал',
        'content.type.anime.label': 'Аниме',
        'content.type.manga.label': 'Манга',
        'content.type.game.label': 'Игра',
        'content.type.music.label': 'Музыка',
        'content.type.other.label': 'Другое',
        'content.creator.book.label': 'Автор',
        'content.creator.movie.label': 'Режиссёр',
        'content.creator.show.label': 'Канал',
        'content.creator.anime.label': 'Студия',
        'content.creator.manga.label': 'Автор',
        'content.creator.game.label': 'Разработчик',
        'content.creator.music.label': 'Исполнитель',
        'content.creator.other.label': 'Автор',
        'content.unit.pages': 'страниц',
        'content.unit.minutes': 'минут',
        'content.unit.episodes': 'серий',
        'content.unit.chapters': 'глав',
        'content.unit.hours': 'часов',
        'content.unit.tracks': 'треков',
        'content.unit.units': 'единиц',
        'content.favorite.add': 'В избранное',
        'content.favorite.remove': 'Убрать из избранного',
        'content.favorite.filter': 'Только избранное',
        'content.layout.list': 'Показать списком',
        'content.layout.grid': 'Показать сеткой',
        'content.stats.finishedByMonth': 'Завершено по месяцам',
        'content.stats.finishedYear': 'за год: {count}',
        'content.stats.avgDays': 'в среднем {count} дн. на одно',
        'content.form.more': 'Подробнее',
        'content.form.type': 'Тип',
        'content.import.new': 'Новые',
        'content.import.updates': 'Изменились в выгрузке',
        'content.import.backward': 'Без галочки — те, что в выгрузке отстают от библиотеки. Отметьте, чтобы всё равно взять статус из выгрузки.',
        'content.import.same.one': '{count} уже в библиотеке, как в выгрузке',
        'content.import.same.few': '{count} уже в библиотеке, как в выгрузке',
        'content.import.same.many': '{count} уже в библиотеке, как в выгрузке',
        'content.import.run': 'Импортировать {created}, обновить {updated}',
        'content.import.doneBoth': 'Импортировано: {created}, обновлено: {updated}',
        'ctypes.show': 'Показывать этот тип',
        'ctypes.hide': 'Скрыть этот тип',
    },
};
