/**
 * Utilities — what its cards say, merged into the dictionary in `core/i18n.ts`
 * (the Chinese is in `core/i18n.zh.ts`, with the rest of that language).
 *
 * Here rather than in the module's own `getTranslations()`: a widget's name is
 * read by the gallery and by saved boards, and a notification source's by the
 * settings page, whether or not the module happens to be loaded.
 */
export const UTILITIES_STRINGS: { en: Record<string, string>; ru: Record<string, string> } = {
    en: {
        'widget.utilities.text': 'Text',
        'widget.utilities.text.desc': 'Your own words, or the top of a note from the vault.',
        'widget.picture.desc': 'A photo or a GIF, from a link or from the vault.',
        'widget.utilities.links': 'Links',
        'widget.utilities.links.desc': 'Notes and addresses you go back to, a tap away.',
        'widget.utilities.recent': 'Recent notes',
        'widget.utilities.recent.desc': 'The notes you last changed, or the files you last opened.',
        'widget.utilities.capture': 'Quick note',
        'widget.utilities.capture.desc':
            'A line to write a thought on, filed in today’s note or one you choose.',
        'widget.utilities.timer': 'Timer',
        'widget.utilities.timer.desc': 'A countdown that tells you when the time is up.',

        'utilities.pick.note': 'Choose a note…',
        'utilities.pick.file': 'Choose a file…',
        'utilities.path.placeholder': 'Folder/Note.md',

        'utilities.text.empty': 'No text yet. Press ⋯ in the card’s header to set it up.',
        'utilities.text.missing': 'That note is not in the vault.',
        'utilities.text.blank': 'The note is empty.',
        'utilities.text.source': 'From',
        'utilities.text.source.own': 'Typed here',
        'utilities.text.source.note': 'A note',
        'utilities.text.placeholder': 'Anything worth keeping in sight. Markdown works.',
        'utilities.text.size': 'Text size',
        'utilities.text.size.sm': 'Small',
        'utilities.text.size.md': 'Normal',
        'utilities.text.size.lg': 'Large',
        'utilities.text.align': 'Align',
        'utilities.text.align.start': 'Left',
        'utilities.text.align.center': 'Centre',
        'utilities.text.face': 'Typeface',
        'utilities.text.face.plain': 'Plain',
        'utilities.text.face.serif': 'Serif',

        'utilities.links.empty': 'No links yet. Press ⋯ in the card’s header to set it up.',
        'utilities.links.dead': 'This leads nowhere: no such note in the vault.',
        'utilities.links.target': 'Note or address',
        'utilities.links.name': 'Name',
        'utilities.links.remove': 'Remove the link',
        'utilities.links.addNote': 'From the vault',
        'utilities.links.addLink': 'Link',

        'utilities.recent.empty': 'Nothing here yet.',
        'utilities.recent.by': 'Show',
        'utilities.recent.by.modified': 'Changed',
        'utilities.recent.by.opened': 'Opened',

        'utilities.capture.empty':
            'Nowhere to write yet. Press ⋯ in the card’s header to set it up.',
        'utilities.capture.placeholder': 'Write it down…',
        'utilities.capture.daily': 'Today’s note',
        'utilities.capture.filed': 'Just written',
        'utilities.capture.to': 'Write to',
        'utilities.capture.to.daily': 'Daily note',
        'utilities.capture.to.note': 'A note',
        'utilities.capture.path.placeholder': 'Inbox.md',
        'utilities.capture.stamp': 'Time',
        'utilities.capture.stamp.on': 'Add',
        'utilities.capture.stamp.off': 'Leave out',
        'utilities.capture.error': 'That could not be written down.',
        'utilities.capture.error.noPath': 'Choose a note to write to first.',
        'utilities.capture.error.noFolder': 'That folder is not in the vault.',
        'utilities.capture.error.notANote': 'That path is a folder, not a note.',

        'utilities.timer.start': 'Start',
        'utilities.timer.stop': 'Stop',
        'utilities.timer.pause': 'Pause',
        'utilities.timer.resume': 'Resume',
        'utilities.timer.held': 'on hold',
        'utilities.timer.reset': 'Reset',
        'utilities.timer.done': 'Time’s up',
        'utilities.timer.until': 'until {time}',
        'utilities.timer.minutes': 'Minutes',
        'utilities.timer.notify.title': 'Time’s up',
        'utilities.timer.notify.body.one': 'The {count}-minute timer has finished.',
        'utilities.timer.notify.body.other': 'The {count}-minute timer has finished.',
        'notify.source.timer': 'Timers',
    },
    ru: {
        'widget.utilities.text': 'Текст',
        'widget.utilities.text.desc': 'Свой текст или начало заметки из хранилища.',
        'widget.picture.desc': 'Фото или GIF — по ссылке или из хранилища.',
        'widget.utilities.links': 'Ссылки',
        'widget.utilities.links.desc': 'Заметки и адреса, к которым вы возвращаетесь.',
        'widget.utilities.recent': 'Недавние заметки',
        'widget.utilities.recent.desc':
            'Заметки, которые вы меняли последними, или недавно открытые файлы.',
        'widget.utilities.capture': 'Быстрая запись',
        'widget.utilities.capture.desc':
            'Строка для мысли: записывается в заметку дня или в выбранную заметку.',
        'widget.utilities.timer': 'Таймер',
        'widget.utilities.timer.desc': 'Обратный отсчёт, который скажет, когда время вышло.',

        'utilities.pick.note': 'Выберите заметку…',
        'utilities.pick.file': 'Выберите файл…',
        'utilities.path.placeholder': 'Папка/Заметка.md',

        'utilities.text.empty': 'Текста пока нет. Нажмите ⋯ в шапке карточки, чтобы настроить.',
        'utilities.text.missing': 'Такой заметки нет в хранилище.',
        'utilities.text.blank': 'Заметка пустая.',
        'utilities.text.source': 'Откуда',
        'utilities.text.source.own': 'Свой текст',
        'utilities.text.source.note': 'Заметка',
        'utilities.text.placeholder': 'То, что хочется держать перед глазами. Markdown работает.',
        'utilities.text.size': 'Размер текста',
        'utilities.text.size.sm': 'Мелкий',
        'utilities.text.size.md': 'Обычный',
        'utilities.text.size.lg': 'Крупный',
        'utilities.text.align': 'Выравнивание',
        'utilities.text.align.start': 'Слева',
        'utilities.text.align.center': 'По центру',
        'utilities.text.face': 'Шрифт',
        'utilities.text.face.plain': 'Обычный',
        'utilities.text.face.serif': 'С засечками',

        'utilities.links.empty':
            'Ссылок пока нет. Нажмите ⋯ в шапке карточки, чтобы настроить.',
        'utilities.links.dead': 'Ссылка никуда не ведёт: такой заметки нет в хранилище.',
        'utilities.links.target': 'Заметка или адрес',
        'utilities.links.name': 'Название',
        'utilities.links.remove': 'Убрать ссылку',
        'utilities.links.addNote': 'Из хранилища',
        'utilities.links.addLink': 'Ссылка',

        'utilities.recent.empty': 'Пока пусто.',
        'utilities.recent.by': 'Показывать',
        'utilities.recent.by.modified': 'Изменённые',
        'utilities.recent.by.opened': 'Открытые',

        'utilities.capture.empty':
            'Писать пока некуда. Нажмите ⋯ в шапке карточки, чтобы настроить.',
        'utilities.capture.placeholder': 'Записать…',
        'utilities.capture.daily': 'Заметка дня',
        'utilities.capture.filed': 'Только что записано',
        'utilities.capture.to': 'Куда',
        'utilities.capture.to.daily': 'Заметка дня',
        'utilities.capture.to.note': 'Заметка',
        'utilities.capture.path.placeholder': 'Входящие.md',
        'utilities.capture.stamp': 'Время',
        'utilities.capture.stamp.on': 'Ставить',
        'utilities.capture.stamp.off': 'Без него',
        'utilities.capture.error': 'Не получилось записать.',
        'utilities.capture.error.noPath': 'Сначала выберите заметку, в которую писать.',
        'utilities.capture.error.noFolder': 'Такой папки нет в хранилище.',
        'utilities.capture.error.notANote': 'Этот путь — папка, а не заметка.',

        'utilities.timer.start': 'Старт',
        'utilities.timer.stop': 'Стоп',
        'utilities.timer.pause': 'Пауза',
        'utilities.timer.resume': 'Продолжить',
        'utilities.timer.held': 'на паузе',
        'utilities.timer.reset': 'Сбросить',
        'utilities.timer.done': 'Время вышло',
        'utilities.timer.until': 'до {time}',
        'utilities.timer.minutes': 'Минут',
        'utilities.timer.notify.title': 'Время вышло',
        'utilities.timer.notify.body.one': 'Таймер на {count} минуту закончился.',
        'utilities.timer.notify.body.few': 'Таймер на {count} минуты закончился.',
        'utilities.timer.notify.body.many': 'Таймер на {count} минут закончился.',
        'notify.source.timer': 'Таймеры',
    },
};
